[[redirects]]
  from = "https://api.diabolical.studio/*"
  to = "https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/frks8kdvmjog/b/DiabolicalGamesStorage/o/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://*.diabolical.studio/*"
  to = "https://diabolical.studio/:splat"
  status = 301
  force = true
